version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: printf "hello \n this \n is \n trial \n circleci \ntest" > my_workspace/echo-output.txt
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace   
          paths:
            - echo-output.txt  
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(wc -l < echo-output.txt) -ge "3" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
